### ISSUE TITLE
README.md missing some context?

### ISSUE THREAD

**Issue by mtvillwock** [ideo/c-delta-challenge#6]
Under `### 1.2: Scoring Creative Qualities for an entire response`, it says: 

>`total, raw, and `... 

Is this sentence missing the word `max`? Also, the word `total` is mentioned but not referred to at any other point in the section – are `total` and `max` the same? Or is `total` related to the `normalized score` in `### 1.3 Scoring Creative Qualities globally`?

**Comment by geeosh** [comment]
@mtvillwock good catch! It's supposed to just be raw and the max, as you'll use those two outputs in Step 1.3. I fixed it here: https://github.com/ideo/c-delta-challenge/pull/7
